apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-footprint
  namespace: aws-footprint
  labels:
    app: aws-footprint
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aws-footprint
  template:
    metadata:
      labels:
        app: aws-footprint
    spec:
      containers:
      - name: aws-footprint
        image: anuclei/aws_footprint:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: AWS_PROFILE
          value: "default" # Change to the AWS profile you want to use
        - name: AWS_REGION
          value: "us-east-1" # Change to the desired AWS region
